### ISSUE TITLE
consider copying all the repository in galaxy tool generation?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda-bot#56] opened 2024-04-09 07:56 UTC
@okolo use case with CRBeam is relevant

I suppose all files should be available, either with tool data or by other other means.

Not all data should be in the tool.

**Comment by dsavchenko** [comment] 2024-10-16 14:26
Probably not all repo but make an option to specify the files needed

**Comment by dsavchenko** [comment] 2024-10-16 14:31
Duplicate of https://github.com/oda-hub/oda-bot/issues/55

**Closed by dsavchenko** 2024-10-16 14:31 UTC
